CREATE TABLE forgot_user_password_token
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER      NOT NULL,
    token   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_forgot_user_password_token PRIMARY KEY (id)
);

ALTER TABLE forgot_user_password_token
    ADD CONSTRAINT uc_forgot_user_password_token_token UNIQUE (token);

ALTER TABLE forgot_user_password_token
    ADD CONSTRAINT uc_forgot_user_password_token_user UNIQUE (user_id);

ALTER TABLE forgot_user_password_token
    ADD CONSTRAINT FK_FORGOT_USER_PASSWORD_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);