CREATE TABLE merchant_request_states
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20)                              NOT NULL,
    CONSTRAINT pk_merchant_request_states PRIMARY KEY (id)
);

CREATE TABLE merchants
(
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tax_id                     VARCHAR(255)                             NOT NULL,
    api_id                     VARCHAR(255),
    merchant_key               VARCHAR(255),
    address                    VARCHAR(255)                             NOT NULL,
    create_at                  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at                 TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    store_name                 VARCHAR(255)                             NOT NULL,
    merchant_request_status_id INTEGER                                  NOT NULL,
    user_id                    INTEGER                                  NOT NULL,
    reviewing_user_id          INTEGER,
    CONSTRAINT pk_merchants PRIMARY KEY (id)
);

ALTER TABLE merchants
    ADD CONSTRAINT FK_MERCHANTS_ON_MERCHANT_REQUEST_STATUS FOREIGN KEY (merchant_request_status_id) REFERENCES merchant_request_states (id);

ALTER TABLE merchants
    ADD CONSTRAINT FK_MERCHANTS_ON_REVIEWING_USER FOREIGN KEY (reviewing_user_id) REFERENCES users (id);

ALTER TABLE merchants
    ADD CONSTRAINT FK_MERCHANTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);