CREATE TABLE users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR(40) NOT NULL,
    phone_number INTEGER     NOT NULL,
    identifier   VARCHAR(20) NOT NULL,
    first_name   VARCHAR(40) NOT NULL,
    last_name    VARCHAR(40) NOT NULL,
    password     VARCHAR(20) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_identifier UNIQUE (identifier);