CREATE TABLE account_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20) NOT NULL,
    CONSTRAINT pk_account_types PRIMARY KEY (id)
);

CREATE TABLE bank_accounts
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password        VARCHAR(8)  NOT NULL,
    balance         FLOAT default 0.0,
    account_number  VARCHAR(20) NOT NULL,
    account_type_id INTEGER     NOT NULL,
    user_id         INTEGER     NOT NULL,
    CONSTRAINT pk_bank_accounts PRIMARY KEY (id)
);

CREATE TABLE type_identifier
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20) NOT NULL,
    CONSTRAINT pk_typeidentifier PRIMARY KEY (id)
);

ALTER TABLE users
    ADD type_identifier_id INTEGER;

ALTER TABLE users
    ALTER COLUMN type_identifier_id SET NOT NULL;

ALTER TABLE bank_accounts
    ADD CONSTRAINT FK_BANK_ACCOUNTS_ON_ACCOUNT_TYPE FOREIGN KEY (account_type_id) REFERENCES account_types (id);

ALTER TABLE bank_accounts
    ADD CONSTRAINT FK_BANK_ACCOUNTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_TYPE_IDENTIFIER FOREIGN KEY (type_identifier_id) REFERENCES type_identifier (id);