CREATE TABLE transaction_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20) NOT NULL,
    CONSTRAINT pk_transaction_types PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description              VARCHAR(255),
    ammount                  FLOAT   NOT NULL,
    address                  VARCHAR(40),
    bank_account_issuer_id   INTEGER NOT NULL,
    bank_account_receiver_id INTEGER NOT NULL,
    transaction_type_id      INTEGER NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_BANK_ACCOUNT_ISSUER FOREIGN KEY (bank_account_issuer_id) REFERENCES bank_accounts (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_BANK_ACCOUNT_RECEIVER FOREIGN KEY (bank_account_receiver_id) REFERENCES bank_accounts (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_TRANSACTION_TYPE FOREIGN KEY (transaction_type_id) REFERENCES transaction_types (id);